[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
nixLibs = ["openssl"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && npm start"
